services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: financedb          # <-- change this
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d financedb"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [app-net]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"   # <-- publish backend to host:8081
    networks: [app-net]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [app-net]

networks:
  app-net:
